// Liste des pays en français et en anglais
export const countries = [
  { code: 'GN', name: 'Guinée', name_en: 'Guinea' },
  { code: 'AF', name: 'Afghanistan', name_en: 'Afghanistan' },
  { code: 'ZA', name: 'Afrique du Sud', name_en: 'South Africa' },
  { code: 'AL', name: 'Albanie', name_en: 'Albania' },
  { code: 'DZ', name: 'Algérie', name_en: 'Algeria' },
  { code: 'DE', name: 'Allemagne', name_en: 'Germany' },
  { code: 'AD', name: 'Andorre', name_en: 'Andorra' },
  { code: 'AO', name: 'Angola', name_en: 'Angola' },
  { code: 'AI', name: 'Anguilla', name_en: 'Anguilla' },
  { code: 'AQ', name: 'Antarctique', name_en: 'Antarctica' },
  { code: 'AG', name: 'Antigua-et-Barbuda', name_en: 'Antigua and Barbuda' },
  { code: 'SA', name: 'Arabie saoudite', name_en: 'Saudi Arabia' },
  { code: 'AR', name: 'Argentine', name_en: 'Argentina' },
  { code: 'AM', name: 'Arménie', name_en: 'Armenia' },
  { code: 'AW', name: 'Aruba', name_en: 'Aruba' },
  { code: 'AU', name: 'Australie', name_en: 'Australia' },
  { code: 'AT', name: 'Autriche', name_en: 'Austria' },
  { code: 'AZ', name: 'Azerbaïdjan', name_en: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas', name_en: 'Bahamas' },
  { code: 'BH', name: 'Bahreïn', name_en: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh', name_en: 'Bangladesh' },
  { code: 'BB', name: 'Barbade', name_en: 'Barbados' },
  { code: 'BE', name: 'Belgique', name_en: 'Belgium' },
  { code: 'BZ', name: 'Belize', name_en: 'Belize' },
  { code: 'BJ', name: 'Bénin', name_en: 'Benin' },
  { code: 'BM', name: 'Bermudes', name_en: 'Bermuda' },
  { code: 'BT', name: 'Bhoutan', name_en: 'Bhutan' },
  { code: 'BY', name: 'Biélorussie', name_en: 'Belarus' },
  { code: 'BO', name: 'Bolivie', name_en: 'Bolivia' },
  { code: 'BA', name: 'Bosnie-Herzégovine', name_en: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana', name_en: 'Botswana' },
  { code: 'BR', name: 'Brésil', name_en: 'Brazil' },
  { code: 'BN', name: 'Brunéi Darussalam', name_en: 'Brunei Darussalam' },
  { code: 'BG', name: 'Bulgarie', name_en: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso', name_en: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi', name_en: 'Burundi' },
  { code: 'KH', name: 'Cambodge', name_en: 'Cambodia' },
  { code: 'CM', name: 'Cameroun', name_en: 'Cameroon' },
  { code: 'CA', name: 'Canada', name_en: 'Canada' },
  { code: 'CV', name: 'Cap-Vert', name_en: 'Cape Verde' },
  { code: 'CL', name: 'Chili', name_en: 'Chile' },
  { code: 'CN', name: 'Chine', name_en: 'China' },
  { code: 'CY', name: 'Chypre', name_en: 'Cyprus' },
  { code: 'CO', name: 'Colombie', name_en: 'Colombia' },
  { code: 'KM', name: 'Comores', name_en: 'Comoros' },
  { code: 'CG', name: 'Congo-Brazzaville', name_en: 'Congo' },
  { code: 'CD', name: 'Congo-Kinshasa', name_en: 'Democratic Republic of the Congo' },
  { code: 'KR', name: 'Corée du Sud', name_en: 'South Korea' },
  { code: 'KP', name: 'Corée du Nord', name_en: 'North Korea' },
  { code: 'CR', name: 'Costa Rica', name_en: 'Costa Rica' },
  { code: 'CI', name: "Côte d'Ivoire", name_en: 'Ivory Coast' },
  { code: 'HR', name: 'Croatie', name_en: 'Croatia' },
  { code: 'CU', name: 'Cuba', name_en: 'Cuba' },
  { code: 'DK', name: 'Danemark', name_en: 'Denmark' },
  { code: 'DJ', name: 'Djibouti', name_en: 'Djibouti' },
  { code: 'DM', name: 'Dominique', name_en: 'Dominica' },
  { code: 'EG', name: 'Égypte', name_en: 'Egypt' },
  { code: 'AE', name: 'Émirats arabes unis', name_en: 'United Arab Emirates' },
  { code: 'EC', name: 'Équateur', name_en: 'Ecuador' },
  { code: 'ER', name: 'Érythrée', name_en: 'Eritrea' },
  { code: 'ES', name: 'Espagne', name_en: 'Spain' },
  { code: 'EE', name: 'Estonie', name_en: 'Estonia' },
  { code: 'US', name: 'États-Unis', name_en: 'United States' },
  { code: 'ET', name: 'Éthiopie', name_en: 'Ethiopia' },
  { code: 'FJ', name: 'Fidji', name_en: 'Fiji' },
  { code: 'FI', name: 'Finlande', name_en: 'Finland' },
  { code: 'FR', name: 'France', name_en: 'France' },
  { code: 'GA', name: 'Gabon', name_en: 'Gabon' },
  { code: 'GM', name: 'Gambie', name_en: 'Gambia' },
  { code: 'GE', name: 'Géorgie', name_en: 'Georgia' },
  { code: 'GH', name: 'Ghana', name_en: 'Ghana' },
  { code: 'GI', name: 'Gibraltar', name_en: 'Gibraltar' },
  { code: 'GR', name: 'Grèce', name_en: 'Greece' },
  { code: 'GD', name: 'Grenade', name_en: 'Grenada' },
  { code: 'GL', name: 'Groenland', name_en: 'Greenland' },
  { code: 'GP', name: 'Guadeloupe', name_en: 'Guadeloupe' },
  { code: 'GT', name: 'Guatemala', name_en: 'Guatemala' },
  { code: 'GG', name: 'Guernesey', name_en: 'Guernsey' },
  { code: 'GY', name: 'Guyana', name_en: 'Guyana' },
  { code: 'GF', name: 'Guyane française', name_en: 'French Guiana' },
  { code: 'HT', name: 'Haïti', name_en: 'Haiti' },
  { code: 'HN', name: 'Honduras', name_en: 'Honduras' },
  { code: 'HK', name: 'Hong Kong', name_en: 'Hong Kong' },
  { code: 'HU', name: 'Hongrie', name_en: 'Hungary' },
  { code: 'IN', name: 'Inde', name_en: 'India' },
  { code: 'ID', name: 'Indonésie', name_en: 'Indonesia' },
  { code: 'IR', name: 'Iran', name_en: 'Iran' },
  { code: 'IQ', name: 'Irak', name_en: 'Iraq' },
  { code: 'IE', name: 'Irlande', name_en: 'Ireland' },
  { code: 'IS', name: 'Islande', name_en: 'Iceland' },
  { code: 'IL', name: 'Israël', name_en: 'Israel' },
  { code: 'IT', name: 'Italie', name_en: 'Italy' },
  { code: 'JM', name: 'Jamaïque', name_en: 'Jamaica' },
  { code: 'JP', name: 'Japon', name_en: 'Japan' },
  { code: 'JE', name: 'Jersey', name_en: 'Jersey' },
  { code: 'JO', name: 'Jordanie', name_en: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan', name_en: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya', name_en: 'Kenya' },
  { code: 'KG', name: 'Kirghizistan', name_en: 'Kyrgyzstan' },
  { code: 'KI', name: 'Kiribati', name_en: 'Kiribati' },
  { code: 'KW', name: 'Koweït', name_en: 'Kuwait' },
  { code: 'LA', name: 'Laos', name_en: 'Laos' },
  { code: 'LS', name: 'Lesotho', name_en: 'Lesotho' },
  { code: 'LV', name: 'Lettonie', name_en: 'Latvia' },
  { code: 'LB', name: 'Liban', name_en: 'Lebanon' },
  { code: 'LR', name: 'Libéria', name_en: 'Liberia' },
  { code: 'LY', name: 'Libye', name_en: 'Libya' },
  { code: 'LI', name: 'Liechtenstein', name_en: 'Liechtenstein' },
  { code: 'LT', name: 'Lituanie', name_en: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg', name_en: 'Luxembourg' },
  { code: 'MK', name: 'Macédoine du Nord', name_en: 'North Macedonia' },
  { code: 'MG', name: 'Madagascar', name_en: 'Madagascar' },
  { code: 'MY', name: 'Malaisie', name_en: 'Malaysia' },
  { code: 'MW', name: 'Malawi', name_en: 'Malawi' },
  { code: 'MV', name: 'Maldives', name_en: 'Maldives' },
  { code: 'ML', name: 'Mali', name_en: 'Mali' },
  { code: 'MT', name: 'Malte', name_en: 'Malta' },
  { code: 'MA', name: 'Maroc', name_en: 'Morocco' },
  { code: 'MQ', name: 'Martinique', name_en: 'Martinique' },
  { code: 'MU', name: 'Maurice', name_en: 'Mauritius' },
  { code: 'MR', name: 'Mauritanie', name_en: 'Mauritania' },
  { code: 'YT', name: 'Mayotte', name_en: 'Mayotte' },
  { code: 'MX', name: 'Mexique', name_en: 'Mexico' },
  { code: 'FM', name: 'Micronésie', name_en: 'Micronesia' },
  { code: 'MD', name: 'Moldavie', name_en: 'Moldova' },
  { code: 'MC', name: 'Monaco', name_en: 'Monaco' },
  { code: 'MN', name: 'Mongolie', name_en: 'Mongolia' },
  { code: 'ME', name: 'Monténégro', name_en: 'Montenegro' },
  { code: 'MS', name: 'Montserrat', name_en: 'Montserrat' },
  { code: 'MZ', name: 'Mozambique', name_en: 'Mozambique' },
  { code: 'MM', name: 'Myanmar', name_en: 'Myanmar' },
  { code: 'NA', name: 'Namibie', name_en: 'Namibia' },
  { code: 'NR', name: 'Nauru', name_en: 'Nauru' },
  { code: 'NP', name: 'Népal', name_en: 'Nepal' },
  { code: 'NI', name: 'Nicaragua', name_en: 'Nicaragua' },
  { code: 'NE', name: 'Niger', name_en: 'Niger' },
  { code: 'NG', name: 'Nigéria', name_en: 'Nigeria' },
  { code: 'NU', name: 'Niue', name_en: 'Niue' },
  { code: 'NO', name: 'Norvège', name_en: 'Norway' },
  { code: 'NC', name: 'Nouvelle-Calédonie', name_en: 'New Caledonia' },
  { code: 'NZ', name: 'Nouvelle-Zélande', name_en: 'New Zealand' },
  { code: 'OM', name: 'Oman', name_en: 'Oman' },
  { code: 'UG', name: 'Ouganda', name_en: 'Uganda' },
  { code: 'UZ', name: 'Ouzbékistan', name_en: 'Uzbekistan' },
  { code: 'PK', name: 'Pakistan', name_en: 'Pakistan' },
  { code: 'PW', name: 'Palaos', name_en: 'Palau' },
  { code: 'PS', name: 'Palestine', name_en: 'Palestine' },
  { code: 'PA', name: 'Panama', name_en: 'Panama' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', name_en: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay', name_en: 'Paraguay' },
  { code: 'NL', name: 'Pays-Bas', name_en: 'Netherlands' },
  { code: 'PE', name: 'Pérou', name_en: 'Peru' },
  { code: 'PH', name: 'Philippines', name_en: 'Philippines' },
  { code: 'PN', name: 'Pitcairn', name_en: 'Pitcairn' },
  { code: 'PL', name: 'Pologne', name_en: 'Poland' },
  { code: 'PF', name: 'Polynésie française', name_en: 'French Polynesia' },
  { code: 'PR', name: 'Porto Rico', name_en: 'Puerto Rico' },
  { code: 'PT', name: 'Portugal', name_en: 'Portugal' },
  { code: 'QA', name: 'Qatar', name_en: 'Qatar' },
  { code: 'RE', name: 'Réunion', name_en: 'Reunion' },
  { code: 'RO', name: 'Roumanie', name_en: 'Romania' },
  { code: 'GB', name: 'Royaume-Uni', name_en: 'United Kingdom' },
  { code: 'RU', name: 'Russie', name_en: 'Russia' },
  { code: 'RW', name: 'Rwanda', name_en: 'Rwanda' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', name_en: 'Saint Kitts and Nevis' },
  { code: 'SM', name: 'Saint-Marin', name_en: 'San Marino' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', name_en: 'Saint Pierre and Miquelon' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', name_en: 'Saint Vincent and the Grenadines' },
  { code: 'SH', name: 'Sainte-Hélène', name_en: 'Saint Helena' },
  { code: 'LC', name: 'Sainte-Lucie', name_en: 'Saint Lucia' },
  { code: 'SV', name: 'Salvador', name_en: 'El Salvador' },
  { code: 'WS', name: 'Samoa', name_en: 'Samoa' },
  { code: 'ST', name: 'Sao Tomé-et-Principe', name_en: 'Sao Tome and Principe' },
  { code: 'SN', name: 'Sénégal', name_en: 'Senegal' },
  { code: 'RS', name: 'Serbie', name_en: 'Serbia' },
  { code: 'SC', name: 'Seychelles', name_en: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone', name_en: 'Sierra Leone' },
  { code: 'SG', name: 'Singapour', name_en: 'Singapore' },
  { code: 'SK', name: 'Slovaquie', name_en: 'Slovakia' },
  { code: 'SI', name: 'Slovénie', name_en: 'Slovenia' },
  { code: 'SO', name: 'Somalie', name_en: 'Somalia' },
  { code: 'SD', name: 'Soudan', name_en: 'Sudan' },
  { code: 'SS', name: 'Soudan du Sud', name_en: 'South Sudan' },
  { code: 'LK', name: 'Sri Lanka', name_en: 'Sri Lanka' },
  { code: 'SE', name: 'Suède', name_en: 'Sweden' },
  { code: 'CH', name: 'Suisse', name_en: 'Switzerland' },
  { code: 'SR', name: 'Suriname', name_en: 'Suriname' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen', name_en: 'Svalbard and Jan Mayen' },
  { code: 'SZ', name: 'Eswatini', name_en: 'Eswatini' },
  { code: 'SY', name: 'Syrie', name_en: 'Syria' },
  { code: 'TJ', name: 'Tadjikistan', name_en: 'Tajikistan' },
  { code: 'TW', name: 'Taïwan', name_en: 'Taiwan' },
  { code: 'TZ', name: 'Tanzanie', name_en: 'Tanzania' },
  { code: 'TD', name: 'Tchad', name_en: 'Chad' },
  { code: 'CZ', name: 'Tchéquie', name_en: 'Czech Republic' },
  { code: 'TF', name: 'Terres australes et antarctiques françaises', name_en: 'French Southern and Antarctic Lands' },
  { code: 'TH', name: 'Thaïlande', name_en: 'Thailand' },
  { code: 'TL', name: 'Timor oriental', name_en: 'East Timor' },
  { code: 'TG', name: 'Togo', name_en: 'Togo' },
  { code: 'TK', name: 'Tokelau', name_en: 'Tokelau' },
  { code: 'TO', name: 'Tonga', name_en: 'Tonga' },
  { code: 'TT', name: 'Trinité-et-Tobago', name_en: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisie', name_en: 'Tunisia' },
  { code: 'TM', name: 'Turkménistan', name_en: 'Turkmenistan' },
  { code: 'TR', name: 'Turquie', name_en: 'Turkey' },
  { code: 'TV', name: 'Tuvalu', name_en: 'Tuvalu' },
  { code: 'UA', name: 'Ukraine', name_en: 'Ukraine' },
  { code: 'UY', name: 'Uruguay', name_en: 'Uruguay' },
  { code: 'VU', name: 'Vanuatu', name_en: 'Vanuatu' },
  { code: 'VA', name: 'Vatican', name_en: 'Vatican City' },
  { code: 'VE', name: 'Venezuela', name_en: 'Venezuela' },
  { code: 'VN', name: 'Viêt Nam', name_en: 'Vietnam' },
  { code: 'WF', name: 'Wallis-et-Futuna', name_en: 'Wallis and Futuna' },
  { code: 'YE', name: 'Yémen', name_en: 'Yemen' },
  { code: 'ZM', name: 'Zambie', name_en: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe', name_en: 'Zimbabwe' }
];

// Fonction utilitaire pour obtenir le nom localisé d'un pays
export function getLocalizedCountryName(countryCode: string, language: string = 'fr'): string {
  const country = countries.find(c => c.code === countryCode);
  if (!country) return countryCode;
  
  return language === 'en' ? (country.name_en || country.name) : country.name;
}

// Fonction pour obtenir le code du pays à partir du nom
export function getCountryCodeByName(countryName: string): string | undefined {
  const country = countries.find(
    c => {
      const nameLower = c.name.toLowerCase();
      const nameEnLower = c.name_en ? c.name_en.toLowerCase() : '';
      const searchLower = countryName.toLowerCase();
      return nameLower === searchLower || nameEnLower === searchLower;
    }
  );
  return country?.code;
}